### PR TITLE
871723: Added circular chart 3d sample in TypeScript and JavaScript.

### PR DESCRIPTION
**Pull request by Soundeswari-Selvam**
**Description:**

Added circular chart 3d samples.

### CODE REVIEW

**Review by Gowrimathi — APPROVED** [review]
Fine

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by Soundeswari-Selvam** [comment]
rebuild

**Review by Gowrimathi — APPROVED** [review]
Fine

**Pull request merged**
